version: "3.7"

services:
    # PHP-FPM - Service
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: lfm_app
        restart: unless-stopped
        tty: true
        working_dir: /var/www

        volumes:
            - ./:/var/www
            - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

        networks:
            - app-network

    # NGINX - Service
    webserver:
        image: nginx:alpine
        container_name: lfm_nginx
        restart: unless-stopped
        tty: true

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./:/var/www
            - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

        networks:
            - app-network

    # MariaDB - Service
    db:
        image: mysql:5.7
        container_name: lfm_database
        restart: unless-stopped
        tty: true

        ports:
            - "3306:3306"

        environment:
            MYSQL_DATABASE: lfm_festival
            MYSQL_ROOT_PASSWORD: padlicoli

        volumes:
            - mariadbdata:/var/lib/mysql
            - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf

        networks:
            - app-network

# Volumes
volumes:
    mariadbdata:
        driver: local

# Networks
networks:
    app-network:
        driver: bridge
